name: example
description: A example of hive_cache.
version: 0.1.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/hive_cache

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.0.0
  http: ^0.12.0+4
  hive_cache:
    path: ..
