name: hive_cache
description: A persistent cache that uses hive.
version: 1.0.0
homepage: https://github.com/marcelgarus/hive_cache

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  hive: ^1.0.0
  meta: ^1.1.8
