name: hive_cache
description: A persistent cache that uses hive.
version: 1.0.0
homepage: https://github.com/marcelgarus/hive_cache

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cached:
    git:
      url: git://github.com/marcelgarus/flutter_cached
      ref: cc46ee3

  hive: ^1.2.0
  hive_flutter: ^0.3.0+2
  rxdart: ^0.23.1
